config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get "home/about" => "homes#about", as: 'about'
  resources :users, only: [:index, :show, :edit, :update] do
    get "search" => "users#search"
    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  end
  resources :chats, only: [:show, :create, :destroy]
  resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  get 'tagsearches/search', to: 'tagsearches#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  #フォローフォロワー
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  # DM機能
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  #ページの閲覧
  has_many :view_counts, dependent: :destroy

  #グループ
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  has_one_attached :profile_image
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user =  User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_books =  @books.created_today
    @yesterday_books = @books.created_yesterday
    @this_week_books = @books.created_this_week
    @last_week_books = @books.created_last_week
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
        redirect_to user_path(current_user.id)
    end
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @books = Book.all
    @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your profile has been updated successfully"
      redirect_to user_path(current_user.id)
    else
      flash.now[:notice] = "error: failed to update"
      render :edit, status: :unprocessable_entity
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_head.html.erb
    <% if user_signed_in? %>
      <li>
        <%= link_to 'Submission Form', new_book_path %>
      </li>
      <li>
        <%= link_to 'Mypage', user_path(current_user.id) %>
      </li>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Sign Up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Log in", new_user_session_path %>
      </li>
    <% end %>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class="table">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<h2>User info</h2>
 <% if @user.errors %>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
  <% end %>
<%= form_with model: @user do |f| %>
  <h4 class="mt-3">Name</h4>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%>
  <h4 class="mt-3">Profile Image</h4>
  <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %>
  <h4 class="mt-3">Introduction</h4>
  <%= f.text_area :introduction, id:"inputIntro"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
  <body class="d-flex flex-column vh-100">
    <main class="mb-auto">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <h2>User info</h2>
            <%= image_tag current_user.get_profile_image(100,100) %>
            <table class="table">
              <tbody>
                <tr></tr>
                <tr>
  	              <th>name</th>
  	              <th><%= @user.name %></th>
                </tr>
                <tr>
  	              <th>introduction</th>
  	              <th><%= @user.introduction %></th>
                </tr>
                <tr>
                  <th>follows</th>
                  <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
                </tr>
                <tr>
                  <th>followers</th>
                  <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
                </tr>
              </tbody>
            </table>

        <div class="row">
          <a class="btn btn-outline-secondary btn-block" href="<%= edit_user_path(current_user.id) %>"><i class="fas fa-user-cog"></i></a></div>
          <h2 class="mt-3">New book</h2>
          <%= form_with model: @book do |f| %>
            <h4 class="mt-3">Title</h4>
            <%= f.text_field :title %>
            <h4 class="mt-3">Opinion</h4>
            <%= f.text_area :body %>
            <div class="form-group">
            <label>Category</label>
              <%= f.text_field :category,class: 'form-control book_category' %>
            </div>
            <%= f.submit 'Create Book', class: "btn btn-success" %>
            
          <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
    		  <h2>Users</h2>
          <%= link_to "グループを作成する", new_group_path %>｜<%= link_to "グループ一覧", groups_path %>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th></th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><a href="<%= user_path(user.id) %>">
                    <%= image_tag user.get_profile_image(100,100) %>
                  </td>
                  <td><%= user.name %></td>
                  <td><a href="<%= user_path(user.id) %>">Show</a></td>
                  <td><%= render "relationships/button", user: user, options: { class: "follow-link" } %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/search.js.erb
$('#search_result').html("<%= j(render 'search', search_book: @search_book ) %>");

app/views/users/show.html.erb
<body class="d-flex flex-column vh-100">
    <main class="mb-auto">

      <div class="container">
        <div class="row">
<div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>
<table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
    <tr>
    <th>follows</th>
    <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
  </tr>
  <tr>
    <td><%= render "relationships/button", user: @user, options: { class: "follow-link" } %></td>
  </tr>
  <tr>
  <td><%= render  "chats/dmButton", user: @user %></td>
    </tr>

</tbody></table>

<div class="row">
  <a class="btn btn-outline-secondary btn-block" href="<%= edit_user_path(@user.id) %>"><i class="fas fa-user-cog"></i></a></div>
      <h2 class="mt-3">New book</h2>
  <%= form_with model: @book do |f| %>
  <h4 class="mt-3">Title</h4>
  <%= f.text_field :title %>
  <h4 class="mt-3">Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
  		<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Likes</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><a href="<%= user_path(book.user_id) %>">
          <%= image_tag book.user.get_profile_image(100,100) %>
        </td>
        <td><a href="<%= book_path(book.id) %>"><%= book.title %></a></td>
        <td><%= book.body %></td>
        <td id="favorite_button_<%= book.id %>">
      <%= render "books/favorites", book: book %>
      </td>
        <td>コメント数: <%= book.book_comments.count %></td>
        <td><%= render "books/static_rate", book: book %></td>
      </tr>
      <% end %>
  </tbody>
</table>
         <%= form_with url:user_search_path(@user), method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: "btn btn-primary" %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>

<h3>投稿数の前日比・前週比</h3>
  <div class="table_width">
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>今日の投稿</th>
        <th>昨日の投稿</th>
        <th>前日比</th>
      </tr>
      </thead>
      <tbody>
        <tr>
	  <td><%= @today_books.count %></td>
	  <td><%= @yesterday_books.count %></td>
        <% if @yesterday_books.count == 0 %>
	  <td>N/A</td>
        <% else %>
	  <td><% @the_day_before =   @today_books.count / @yesterday_books.count  %>
	  <%= (@the_day_before * 100).round %>%</td>
        <% end %>
        </tr>
      </tbody>
    </table>
      
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>今週の投稿</th>
        <th>先週の投稿</th>
        <th>先週比</th>
      </tr>
      </thead>
      <tbody>
        <tr>
	  <td><%= @this_week_books.count %></td>
	  <td><%= @last_week_books.count %></td>
        <% if @last_week_books.count == 0 %>
	  <td>N/A</td>
        <% else %>
	  <td><% @the_week_before = @this_week_books.count / @last_week_books.count  %>
	  <%= (@the_week_before * 100).round %>%</td>
        <% end %>
        </tr>
      </tbody>
    </table>
        <h2>7日分の投稿数</h2>
    <table class="table table-bordered ">
      <tr>
        <th>6日前</th>
        <th>5日前</th>
        <th>4日前</th>
        <th>3日前</th>
        <th>2日前</th>
        <th>1日前</th>
        <th>今日</th>
      </tr>
      <tr>
        <td><%= @books.created_today.count %></td>
        <td><%= @books.created_yesterday.count %></td>
        <td><%= @books.created_2day_ago.count %></td>
        <td><%= @books.created_3day_ago.count %></td>
        <td><%= @books.created_4day_ago.count %></td>
        <td><%= @books.created_5day_ago.count %></td>
        <td><%= @books.created_6day_ago.count %></td>
      </tr>
    </table>
    <canvas id="WeeklyChart"></canvas>
  <script>
    $(document).on('turbolinks:load', function() {
      var ctx = document.getElementById("WeeklyChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
          datasets: [
            {
              label: '投稿した本の数',
              data: [
                <%= @books.created_6day_ago.count %>,
                <%= @books.created_5day_ago.count %>,
                <%= @books.created_4day_ago.count %>,
                <%= @books.created_3day_ago.count %>,
                <%= @books.created_2day_ago.count %>,
                <%= @books.created_yesterday.count %>,
                <%= @books.created_today.count %>
              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.5
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>
    </main>
  </body>
</html>