config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get "home/about" => "homes#about", as: 'about'
  resources :users, only: [:index, :show, :edit, :update] do
    get "search" => "users#search"
    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  end
  resources :chats, only: [:show, :create, :destroy]
  resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  get 'tagsearches/search', to: 'tagsearches#search'
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :week_favorites, -> { where(created_at: Time.current.all_week) }
  validates :title, presence: true
  validates :body, length: { minimum: 1, maximum: 200 }
  has_many :view_counts, dependent: :destroy
  validates :category, presence: true
  
  scope :created_today, -> { where(created_at: Time.current.all_day) } 
  scope :created_yesterday, -> { where(created_at: Time.current.yesterday.all_day) } 
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: Time.current.all_week) } 
  scope :created_last_week, -> { where(created_at: Time.current.last_week.all_week) } 

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  protect_from_forgery

  before_action :authenticate_user!, except: [:top, :about]

  def new
    @book = Book.new
  end

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(post_image_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Your book has been created successfully"
      redirect_to book_path(@book.id)
    else
      flash.now[:notice] = "error: failed to create"
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
        redirect_to books_path
    end
  end

  def update
    @user = current_user
    @books = Book.all
    @book = Book.find(params[:id])
    if @book.update(post_image_params)
      flash[:notice] = "Your book has been updated successfully"
      redirect_to book_path(@book.id)
    else
      flash.now[:notice] = "error: failed to update"
      render :edit
    end
  end

  def index
    if params[:latest]
      @books = Book.latest
    elsif params[:old]
      @books = Book.old
    elsif params[:star_count]
      @books = Book.star_count
    else
      @books = Book.all
    end
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    current_user.view_counts.create(book_id: @book.id)
    @book_comment = BookComment.new
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def post_image_params
    params.require(:book).permit(:title, :body, :image, :star, :category)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<table>
  <tbody>
    <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to user_path(book_comment.user) do %>
          <%= image_tag book_comment.user.get_profile_image(100, 100) %><br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <td>
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-sm btn-danger float-end", remote: true, data: {"turbolinks" => false} %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_count.html.erb
コメント数： <%= book.book_comments.count %>

app/views/books/_favorites.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
      <span style="color: red;"><%= book.favorites.count %></span>
    <% end %>
  </p>
  <% else %>
  <p>
      <%= link_to book_favorites_path(book), method: :post, remote: true do %>
        <i class="fas fa-heart" aria-hidden="true"></i>
        <span><%= book.favorites.count %></span>
      <% end %>
  </p>
<% end %>

app/views/books/_list.html.erb
<% books.each do |book| %>
  <div>
    <%= link_to book_path(book.id) do %>
      <%= image_tag book.get_image %>
    <% end %>

    <p>User Profile：<%= image_tag book.user.get_profile_image(100,100) %></p>
    <p>Title：<%= book.title %></p>
    <p>Body：<%= book.body %></p>
    <p>Username：<%= book.user.name %></p>
  </div>
<% end %>

app/views/books/_static_rate.html.erb
<div id="star_<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= book.id %>');
  if (elem == null) return;
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= book.star %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/books/edit.html.erb
<h2>Book info</h2>
<h3>Editing Book</h3>
<%= form_with model: @book do |f| %>
  <h4 class="mt-3">Image</h4>
  <%= f.file_field :image, class: "col-xs-12", accept: "image/*" %>
  <h4 class="mt-3">Title</h4>
  <%= f.text_field :title %>
  <h4 class="mt-3">Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book', class: "btn btn-success" %>
<% end %>
<%= link_to "Back", books_path %>
<%= link_to "Show", book_path(@book) %>

app/views/books/index.html.erb
  <body class="d-flex flex-column vh-100">
     <% if @book.errors %>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
      <% end %>
    <main class="mb-auto">

      <div class="container">
        <div class="row">
<div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag current_user.get_profile_image(100,100) %>
<table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
    <tr>
    <th>follows</th>
    <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
  </tr>
</tbody></table>

<div class="row">
  <a class="btn btn-outline-secondary btn-block" href="<%= edit_user_path(current_user.id) %>"><i class="fas fa-user-cog"></i></a></div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model: @book do |f| %>
  <h4 class="mt-3">Title</h4>
  <%= f.text_field :title %>
  <h4 class="mt-3">Opinion</h4>
  <%= f.text_area :body %>
   <% if @book.id.nil? %>
    <div class="form-group" id="star">
      <%= f.label :star %>
      <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;
  
        elem.innerHTML = ""
        let opt = {  
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[star]',
        };
        raty(elem, opt);
      });
    </script>
  <% else %>
    <div class="form-group">
      <%= render "static_rate", book: @book %>
    </div>
  <% end %>
  <div class="form-group">
  <label>Category</label>
  <%= f.text_field :category,class: 'form-control book_category' %>
</div>
  <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
  		<h2>Books</h2>
      <%= link_to '新しい順', books_path(latest: "true") %>
      <%= link_to '古い順', books_path(old: "true") %>
      <%= link_to '評価の高い順', books_path(star_count: "true") %>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Likes</th>
      <th>Comments</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><a href="<%= user_path(book.user_id) %>">
          <%= image_tag book.user.get_profile_image(60,60) %>
        </td>
        <td><a href="<%= book_path(book.id) %>"><%= book.title %></a></td>
        <td><%= book.body %></td>
    <td id="favorite_button_<%= book.id %>"> 
      <%= render "books/favorites", book: book %>
    </td>
    <td>
      <%= render "books/count", book: book %>
    </td>
    <td>閲覧数: <%= book.view_counts.count %></td>
    <td><%= render "books/static_rate", book: book %></td>
    <td><%= book.created_at %></td>
    <td>
      <% if book.category.present? %>
        <%=link_to book.category,tagsearches_search_path(content:book.category)%>
      <% end %>
</td>
      </tr>
      <% end %>
  </tbody>
</table>
    </main>
  </body>
</html>

app/views/books/new.html.erb
<h1>Submission Form</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
  <h4 class="mt-3">Image</h4>
  <%= f.file_field :image, class: "col-xs-12", accept: "image/*" %>
  <h4 class="mt-3">Title</h4>
  <%= f.text_field :title %>
  <h4 class="mt-3">Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book', class: "col-xs-12 btn btn-success" %>
<% end %>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= image_tag current_user.get_profile_image(100,100) %>
            <table class="table">
              <tbody>
                <tr></tr>
                <tr>
  	              <th>name</th>
  	              <th><%= @book.user.name %></th>
                </tr>
                <tr>
            	    <th>introduction</th>
            	    <th><%= @book.user.introduction %></th>
                </tr>
                  <tr>
    <th>follows</th>
    <th><%= link_to @book.user.followings.count, user_followings_path(@book.user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to @book.user.followers.count, user_followers_path(@book.user) %></th>
  </tr>
  <tr><td><%= render "relationships/button", user: @book.user, options: { class: "follow-link" } %></td></tr>
              </tbody>
            </table>
      <h2 class="mt-3">New book</h2>
        <%= form_with model: @book_new, local:true do |f| %>
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
          <%= f.label :opinion %>
          <%= f.text_area :body, class: 'form-control book_body' %>
           <% if @book_new.id.nil? %>
    <div class="form-group" id="star">
      <%= f.label :star %>
      <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;
  
        elem.innerHTML = ""
        let opt = {  
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[star]',
        };
        raty(elem, opt);
      });
    </script>
  <% else %>
    <div class="form-group">
      <%= render "static_rate", book: @book_new %>
    </div>
  <% end %>
  <div class="form-group">
  <label>Category</label>
  <%= f.text_field :category,class: 'form-control book_category' %>
  </div>
          <%= f.submit class: 'btn btn-success' %>
        <% end %>
      </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image(50, 50)%><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
            <td>閲覧数: <%= @book.view_counts.count %></td>
            <td><%= render "books/static_rate", book: @book %></td>
            <td>
            <% if @book.category.present? %>
              <%=link_to@book.category,tagsearches_search_path(content:@book.category)%>
            <% end %>
</td>
        </tr>
      </table>
      <div id="comment_index">
        <%= render "books/comment", book: @book %>
      </div>
      <div id="comment-form">
        <%= render "book_comments/form" , { book: @book , book_comment: @book_comment } %>
      </div>
    </div>
  </div>
</div>